<div class="billet">
	<div class="topProjet">
		<p class="nomProjet"><?= $listeProjetSelection[$i]->getProjetnom()?></p>
		<p class="auteur">Auteur: <span class="nomPP"><?= $listeProjetSelection[$i]->getProjetusername()?></p>
		<p class="auteur"><?= $listeProjetSelection[$i]->getProjetdate()?></p>
	</div>
	<div class="descProjet">
		<p class="">Profils recherchés : <?= $listeProjetSelection[$i]->getProfilrecherche()?></p>
		<p class="">Durée du projet : <?= $listeProjetSelection[$i]->getTempstravail()?></p>
		<p>Description : <br> <?= $listeProjetSelection[$i]->getProjetdescription()?></p>
	</div>
	<div class="col-3">
		<div class="content-img">
		<img src="sources/images/photo_project/<?= $listeProjetSelection[$i]->getPhoto()?>" alt="">
		</div>

	<?php
	$res=mysqli_query($db,"SELECT type FROM user WHERE username = '".$_SESSION['username']."'");
	$type=mysqli_fetch_assoc($res);
	if($type['type'] == 'dev') {
		echo '<form action="index.php?page=dev-projets" method="POST">
			<input type="hidden" name="idp" value="'.$listeProjetSelection[$i]->getProjetid().'">
			<input type="submit" name="voirFicheProjet" value="Voir plus de détails">
			<input type="submit" class="back" name="postulerProjet" value="Postuler">
			</form>';
		}
		else if ($type['type'] == 'pp') {
			echo '<form action="index.php?page=pp-projets" method="POST">
			<input type="hidden" name="idp" value="'.$listeProjetSelection[$i]->getProjetid().'">
			<input type="submit" class="back" name="voirFicheProjet" value="Voir plus de détails">
			</form>';
		}
	?>
	</div>
</div>