<div class="billet">
	<div class="topProjet">
		<p class="nomProjet"><?= $listeProjetSelection[$i]->getProjetnom()?></p>
		<p class="auteur">Auteur: <span class="nomPP"><?= $listeProjetSelection[$i]->getProjetusername()?></p>
		<p class="auteur"><?= $listeProjetSelection[$i]->getProjetdate()?></p>
	</div>
	<div class="descProjet">
		<p class="">Profils recherchés : <?= $listeProjetSelection[$i]->getProfilrecherche()?></p>
		<p class="">Durée du projet : <?= $listeProjetSelection[$i]->getTempstravail()?></p>
		<p>Description : <br> <?= $listeProjetSelection[$i]->getProjetdescription()?></p>
	</div>
	<div class="col-3">
		<div class="content-img">
		<img src="sources/images/photo_project/<?= $listeProjetSelection[$i]->getPhoto()?>" alt="">
		</div>
	<p>Pour voir l'intégralité du projet merci de vous inscrire.</p>
	<a class="back right" href="index.php?page=dev-inscription">S'incrire</a>
	</div>
</div>