<div class="billet projet-search">
	<h3><?= $listeProjetSearch[$i]->getProjetnom()?></h3>
	<h3><?= $listeProjetSearch[$i]->getProjetdescription()?></h3>
	<h3><?= $listeProjetSearch[$i]->getProjetusername()?></h3>
	<h3><?= $listeProjetSearch[$i]->getProfilrecherche()?></h3>
	<h3><?= $listeProjetSearch[$i]->getTempstravail()?></h3>
	<h3><?= $listeProjetSearch[$i]->getProjetdate()?></h3>
	<h3><?= $listeProjetSearch[$i]->getStatut()?></h3>
</div>