<div class="billet">
	<div class="topProjet">
		<p class="nomProjet"><?= $listeProjetSearch[$i]->getProjetnom()?></p>
		<p class="auteur">Auteur: <span class="nomPP"><?= $listeProjetSearch[$i]->getProjetusername()?></span></p>
	</div>
	<div class="descProjet">
		<p>Description: <?= $listeProjetSearch[$i]->getProjetdescription()?></p>
		<p>Profils recherchés: <?= $listeProjetSearch[$i]->getProfilrecherche()?></p>
		<p>Durée du projet: <?= $listeProjetSearch[$i]->getTempstravail()?></p>
		<p>Date de publication: <?= $listeProjetSearch[$i]->getProjetdate()?></p>
		<p>Statut: <?= $listeProjetSearch[$i]->getStatut()?></p>
	</div>
</div>