<div class="billet">
	<div class="topProjet">
		<p class="nomProjet"><?= $listeProjetEncours[$i]->getProjetnom()?></p>
		<p class="auteur">Auteur: <span class="nomPP"><?= $listeProjetEncours[$i]->getProjetusername()?></span></p>
	</div>
	<div class="descProjet">
		<p>Description: <?= $listeProjetEncours[$i]->getProjetdescription()?></p>
		<p>Profils recherchés: <?= $listeProjetEncours[$i]->getProfilrecherche()?></p>
		<p>Durée du projet<?= $listeProjetEncours[$i]->getTempstravail()?></p>
		<p>Date de publication<?= $listeProjetEncours[$i]->getProjetdate()?></p>
		<p>Statut: <?= $listeProjetEncours[$i]->getStatut()?></p>
	</div>
	<?php
	if($_SESSION['type'] === 'pp') {
		echo '<form action="index.php?page=pp-projets" method="POST">
			<input type="hidden" name="idp" value="'.$listeProjetEncours[$i]->getProjetid().'">
			<input type="submit" name="voirFicheProjet" value="Voir plus de détails">
		</form>';
	}
	else {
		echo '<form action="index.php?page=dev-projets" method="POST">
			<input type="hidden" name="idp" value="'.$listeProjetEncours[$i]->getProjetid().'">
			<input type="submit" name="voirFicheProjet" value="Voir plus de détails">
		</form>';
	} ?>
</div>