<div class="billet projet-termine">
	<h3><?= $listeProjetTermine[$i]->getProjetnom()?></h3>
	<h3><?= $listeProjetTermine[$i]->getProjetdescription()?></h3>
	<h3><?= $listeProjetTermine[$i]->getProjetusername()?></h3>
	<h3><?= $listeProjetTermine[$i]->getProfilrecherche()?></h3>
	<h3><?= $listeProjetTermine[$i]->getTempstravail()?></h3>
	<h3><?= $listeProjetTermine[$i]->getProjetdate()?></h3>
	<h3><?= $listeProjetTermine[$i]->getStatut()?></h3>
</div>