<div class="billet">
	<div class="topProjet">
		<p class="nomProjet"><?= $listeProjetTermine[$i]->getProjetnom()?></p>
		<p class="auteur">Auteur: <span class="nomPP"><?= $listeProjetTermine[$i]->getProjetusername()?></span></p>
	</div>
	<div class="descProjet">
		<p>Description: <?= $listeProjetTermine[$i]->getProjetdescription()?></p>
		<p>Profils recherchés: <?= $listeProjetTermine[$i]->getProfilrecherche()?></p>
		<p>Durée du projet<?= $listeProjetTermine[$i]->getTempstravail()?></p>
		<p>Date de publication<?= $listeProjetTermine[$i]->getProjetdate()?></p>
		<p>Statut: <?= $listeProjetTermine[$i]->getStatut()?></p>
	</div>
</div>