<div class="billet projet-encours">
	<h3><?= $listeProjetEncours[$i]->getProjetnom()?></h3>
	<h3><?= $listeProjetEncours[$i]->getProjetdescription()?></h3>
	<h3><?= $listeProjetEncours[$i]->getProjetusername()?></h3>
	<h3><?= $listeProjetEncours[$i]->getProfilrecherche()?></h3>
	<h3><?= $listeProjetEncours[$i]->getTempstravail()?></h3>
	<h3><?= $listeProjetEncours[$i]->getProjetdate()?></h3>
	<h3><?= $listeProjetEncours[$i]->getStatut()?></h3>
</div>