<div class="inscription">
	<div class="left">
		<img src="sources/images/logo_name.png" alt="phone">
		<p class="bold green-black font-l">Votre compte à bien était créé !</p>
		<p class="green-black">
		Accéder en ilimité et gratuitement à votre dashboard.</p>
	</div>
	<div class="right">
		<p class="bold green-black">Connectez vous</p>
		<form method='POST' action='index.php' class='loginForm'>
			<input type='email' name='logmail' placeholder='Email'>
			<input type='password' name='logpass' placeholder='Mot de passe'>
			<input type='submit' name='logsubmit' value='Connexion'>
		</form> 
	</div>
</div>