<?php require('apps/dev-nav.php'); ?>

FICHE PROJET DEV

Nom du projet: <?=$data->getProjetnom()?><br>
Statut du projet: <?=$data->getStatut()?><br>
Date de post du projet: <?=$data->getProjetdate()?><br>
Auteur: <?=$data->getProjetusername()?><br>
Description du projet: <?=$data->getProjetdescription()?><br>
Profil recherché: <?=$data->getProfilrecherche()?><br>
Temps de travail estimé: <?=$data->getTempstravail()?><br>

<?php
	if($data->getStatut() === 'selection') {
		echo '<form action="index.php?page=dev-projets" method="POST">
			<input type="hidden" name="idp" value="'.$data->getProjetid().'">
			<input type="submit" name="postulerFicheProjet" value="Postuler">
			</form>';
	}
?>

<a href="index.php?page=dev-profil">Back</a>