<h1>Inscription dev</dev>
<form method="POST" enctype="multipart/form-data" action="index.php?page=dev-inscription">
	<?= $msgInscription ?><br>
	<label for="username">Nom d'utilisateur : </label><input type="text" name="username" required><br>
	<label for="email">Email : </label><input type="email" name="email" required><br>
	<label for="password">Mot de passe : </label><input type="password" name="password" required><br>
	<label for="confpass">Confirmation du mot de passe : </label><input type="password" name="confpass" required><br>
	<!-- <input type="file" name="photo_pp_dev" accept="image/bmp,image/gif,image/png,image/jpeg,image/x-ms-bmp"> -->
	<input type="submit" name="create" value="Créer mon compte">
</form>