<a href="index.php" class="back">retour</a>
<hr>
<div class="inscription">
<div class="left">
<img src="sources/images/phone_G.png" alt="phone">
<p class="bold green-black font-l">Ne ratez plus rien !</p>
<p class="green-black">
Accédez à givemeaproject.fr sur votre téléphone mobile !</p>
</div>
<div class="right">
<p class="bold green-black">Developer</p>
<form method="POST" enctype="multipart/form-data" action="index.php?page=dev-inscription">
	<?= $msgInscription ?><br>
	<input type="text" name="username" placeholder="nom d'utilisateur" required><br>
	<input type="email" name="email" placeholder="e-mail" required><br>
	<input type="password" name="password" placeholder="mot de passe" required>
	<input type="password" name="confpass" placeholder="confirmation du mot de passe" required><br>
	<!-- <input type="file" name="photo_pp_dev" accept="image/bmp,image/gif,image/png,image/jpeg,image/x-ms-bmp"> -->
	<input type="submit" name="create" value="Inscription">
</form>
</div>
</div>