<?php require('apps/dev-nav.php'); ?>
<h1>Projets en cours</h1>
		<?php 
			$i=0;
			while (isset($listeProjetEncours[$i]))
		    {
			    require ('views/billet-projet-encours.phtml');
			    $i++;
			}
		?>
<h1>Projets en attente de validation</h1>
		<?php 
			$i=0;
			while (isset($listeProjetSelection[$i]))
		    {
			    require ('views/billet-projet-encours.phtml');
			    $i++;
			}
		?>

<h1>Projets terminés</h1>