<div class="modifprofil-dev">
	<form action="index.php?page=dev-modifprofil" method="POST" enctype="multipart/form-data">
		<input placeholder="Nom d'utilisateur" type="text" name="modifUsername" value="<?= $content['username']?>"><br>
		<input placeholder="Adresse email" type="text" name="modifEmail" value="<?= $content['email']?>"><br>
		<input placeholder="Nom" type="text" name="modifNom" value="<?= $content['nom']?>"><br>
		<input placeholder="Prénom" type="text" name="modifPrenom" value="<?= $content['prenom']?>"><br>
		<textarea placeholder="Présentation" name="modifPresentation"><?= $content['presentation']?></textarea><br>
		<input placeholder="Mon compte Paypal" type="email" name="modifPaypal" value="<?= $content['paypal']?>"><br>
		<textarea placeholder="Mes compétences" name="modifCompetences"><?= $content['competences']?></textarea><br>
		<img src="sources/images/photo_pp_dev/<?= $content['photo']?>" alt="">
		<input type="file" name="photo_pp_dev" accept="image/bmp,image/gif,image/png,image/jpeg,image/x-ms-bmp"> 
		<input type="submit" name="submitModifProfil" value="Modifier">
	</form>
	<form action="index.php?page=pp-modifprofil" method="POST">
		<input type="password" name="modifXPassword" placeholder="Votre mot de passe actuel"><br>

		<input type="password" name="modifPassword" placeholder="Votre nouveau mot de passe"><br>

		<input type="password" name="modifConfPassword" placeholder="Confirmez votre nouveau mot de passe"><br>

		<input type="submit" name="submitModifPassword" value="Modifier mon mot de passe">
	</form>
	<form action="index.php?page=pp-modifprofil" method="POST">
		<input type="submit" name="supprimerCompte" value="Supprimer mon compte">
	</form>
</div>