<footer>
	<div class="footer-wrap">
		<div class="col">
			<ul>
				<li><a href="">Contact</a>&nbsp;-</li>
				<li><a href="">A propos</a>&nbsp;-</li>
				<li><a href="">CGU</a>&nbsp;-</li>
				<li><a href="">Dons</a></li>
			</ul>
		</div>
		<div class="col">
			<p>Give Me A Project &copy; 2014</p>
		</div>
		<div class="col">
			<ul class="icone">
				<a href="#"><li class="icone-1 animated zoomIn"></li></a>
				<!-- <a href="#"><li class="icone-2 animated rotateIn"></li></a> -->
				<a href="#"><li class="icone-3 animated zoomIn"></li></a>
				<a href="#"><li class="icone-4 animated rotateIn"></li></a>
				<!-- <a href="#"><li class="icone-5 animated zoomIn"></li></a> -->
			</ul>
		</div>
	</div>
</footer>