<footer>
	<div class="footer-wrap">
		<div class="col">
			<ul>
				<li><a href="">Contact</a></li>
				<li><a href="">A propos</a></li>
				<li><a href="">CGU</a></li>
				<li><a href="">Dons</a></li>
			</ul>
		</div>
		<div class="col">
			<p>Give Me A Project &copy; 2014</p>
		</div>
		<div class="col">
			<a href=""><i class="fa fa-twitter fa-fw social"></i></a><a href=""><i class="fa fa-facebook fa-fw social"></i></a>
			<a href=""><i class="fa fa-linkedin fa-fw social"></i></a><a href=""><i class="fa fa-git fa-fw social"></i></a>
		</div>
	</div>
</footer>