<header>
<h1 class="titre">Give Me a Project</h1>

	<?php 
		if(isset($_SESSION['username'])) {
			echo "<div class='logged'>
				<form method='POST' action='index.php' class='disconnect'>
					<input type='submit' name='disconnect' value='déconnexion'>
				</form>
				<h2 class='headerUser'>".$_SESSION['username']."</h2>
				<a href=''><i class='fa fa-cog'></i></a>
			</div>";
		}
		else { 
			echo "<form method='POST' action='index.php' class='loginForm'>
					<input type='email' name='logmail' placeholder='Email'>
					<input type='password' name='logpass' placeholder='Mot de passe'>
					<input type='submit' name='logsubmit' value='Connexion'>
				</form>"; } 
	?>
</header>