<div id="slider">
	<img id="image" src="sources/images/slider/slider01.jpg" alt="">
</div>
<div class="content">
	<div class="insc-box">
			<div class="insc"><a href="index.php?page=pp-inscription"><p>Je suis à la recherche de talents pour mes projet</p><div class="insc-hover"><i class="fa fa-smile-o fa-4x"></i></div></a></div>
			<div class="insc"><a href="index.php?page=dev-inscription"><p>Je suis à la recherche d'un projet ambitieux</p><div class="insc-hover"><i class="fa fa-smile-o fa-4x"></i></div></a></div>
	</div>
	<div class="temoignage">
		<div class="temoignage-photo">
			<img src="sources/images/profil/02.jpg" alt="">
		</div>
		<div class="temoignage-texte">
			<p><i class="fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto, molestias voluptatem sed optio a earum sequi sunt placeat, numquam, veniam nesciunt quod ipsa facilis. <i class="fa fa-quote-right"></i></p>
			<p class="temoignage-auteur">~ Arnaud C.</p>
		</div>
	</div>
	<div class="temoignage">
		<div class="temoignage-photo">
			<img src="sources/images/profil/02.jpg" alt="">
		</div>
		<div class="temoignage-texte">
			<p><i class="fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto, molestias voluptatem sed optio a earum sequi sunt placeat, numquam, veniam nesciunt quod ipsa facilis. <i class="fa fa-quote-right"></i></p>
			<p class="temoignage-auteur">~ Arnaud C.</p>
		</div>
	</div>
	<div class="temoignage">
		<div class="temoignage-photo">
			<img src="sources/images/profil/02.jpg" alt="">
		</div>
		<div class="temoignage-texte">
			<p><i class="fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. In iusto, molestias voluptatem sed optio a earum sequi sunt placeat, numquam, veniam nesciunt quod ipsa facilis. <i class="fa fa-quote-right"></i></p>
			<p class="temoignage-auteur">~ Arnaud C.</p>
		</div>
	</div>
</div>
<script src="sources/js/script.js"></script>