<a class="back" href="index.php">Retour</a>
<hr>
<div class="search">
<form action="index.php?page=liste-projets" method="POST">
	<input type="search" name="search" placeholder="chercher">
	<button type="submit" name="searchBtn"><i class="fa fa-search"></i></button>
</form>
</div>
<hr>
<a class="back" href="index.php?page=liste-projets">Tout afficher</a>
<div class="liste-projet">
	<?php 
		$i=0;
		while (isset($listeProjetSelection[$i]))
	    {
		    require ('views/billet-projet-logout.phtml');
		    $i++;
		}
	?>
	<?php 
		$iSearch=0;
		while (isset($listeProjetSearch[$iSearch]))
	    {
		    require ('views/billet-projet-search-logout.phtml');
		    $iSearch++;
		}
	?>
</div>