<?php require('apps/pp-nav.php'); ?>

Nom du projet: <?=$data->getProjetnom()?><br>
Statut du projet: <?=$data->getStatut()?><br>
Date de post du projet: <?=$data->getProjetdate()?><br>
Auteur: <?=$data->getProjetusername()?><br>
Description du projet: <?=$data->getProjetdescription()?><br>
Profil recherché: <?=$data->getProfilrecherche()?><br>
Temps de travail estimé: <?=$data->getTempstravail()?><br>

<a href="index.php?page=pp-profil">Back</a>