<div class="content"><h1>Inscription porteur de projet</dev>
	<form method="POST" action="index.php?page=pp-inscription">
		<?= $msgInscription ?><br>
		<label for="username">Nom d'utilisateur : </label><input type="text" name="username" required><br>
		<label for="email">Email : </label><input type="email" name="email" required><br>
		<label for="password">Mot de passe : </label><input type="password" name="password" required><br>
		<label for="confpass">Confirmation du mot de passe : </label><input type="password" name="confpass" required><br>
		<input type="submit" name="create" value="Créer mon compte">
	</form>
</div>