<?php require("apps/pp-nav.php"); ?>

<form method="POST" action="index.php?page=pp-post" id="postform" enctype="multipart/form-data">
	<input type="text" name="projetnom" placeholder="Nom du projet"><br>
	<textarea name="projetdescription" placeholder="Description du projet..."></textarea><br>
	<input type="text" name="projetwords" placeholder="Mot clés associés au projet (séparés d'une virgule)"><br>
	<textarea name="profilrecherche" type="text" placeholder="Profil recherché"></textarea><br>
	<select name="tempstravail" form="postform">
		<option value="">Sélectionnez le temps de travail nécessaire</option>
		<option value="1">moins d'une semaine</option>
		<option value="2">1 semaine</option>
		<option value="3">2 semaine</option>
		<option value="4">3 semaine</option>
		<option value="5">1 mois ou plus</option>
		<option value="6">indeterminé</option>
	</select><br>
	<input type="file" name="photo_project" accept="image/bmp,image/gif,image/png,image/jpeg,image/x-ms-bmp">
	<input type="submit" name="projetpost" value="Créer le projet">
</form>