<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="UTF-8">
	<title>Give Me a Project</title>
	<script src="sources/js/jquery-2.1.1.min.js"></script>
	<link rel="stylesheet" type="text/css" href="sources/css/reset.css">
	<link rel="stylesheet" type="text/css" href="sources/css/style.css">
</head>
<body>
	<?php require("apps/header.php"); ?>
	<?php require("apps/content.php"); ?>
	<?php require("apps/footer.php"); ?>
</body>
</html>