<!DOCTYPE html>
<html lang="fr-FR">
<head>
	<meta charset="UTF-8">
	<title>Give Me a Project</title>
	<script src="sources/js/jquery-2.1.1.min.js"></script>
	<script src="sources/js/menu-deroulant.js"></script>
	<link rel="stylesheet" type="text/css" href="sources/css/reset.css">
	<link rel="stylesheet" type="text/css" href="sources/css/style.css">
	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>
<body>
	<?php require("apps/header.php"); ?>
	<div class="content">
	<?php require("apps/".$page.".php"); ?>
	</div>
	<?php require("apps/footer.php"); ?>
</body>
</html>